Fix typo

diff --git a/bin/create-frontend b/bin/create-frontend
--- a/bin/create-frontend
+++ b/bin/create-frontend
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 if [ $UID == "root" ]; then
-    echo "ERROR: Superuser is now allowed." >&2
+    echo "ERROR: Superuser is not allowed." >&2
     exit 1
 fi
 
